# Generated by Django 5.1.5 on 2025-02-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_campaignimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="amount",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
