# Generated by Django 5.1.3 on 2025-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_campaign_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="amount_received",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="campaign",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
