# Generated by Django 5.1.3 on 2025-02-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_campaign_amount_received_campaign_payment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="amount_received",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="payment_status",
        ),
    ]
